### ISSUE TITLE
Reuse chain?

### ISSUE THREAD

**Issue by jhillyerd** [justinas/alice#3]
I haven't tried Alice yet, but I am curious if the example below is possible:

```
stdStack := alice.New(gzipHandler, ratelimitHandler, securityHandler, authHandler)
indexChain := stdStack.Then(indexHandler)
resourceChain := stdStack.Then(resourceHandler)
```

If that works, it would be nice to have it mentioned in the docs.

**Comment by spinningarrow** [comment]
This is exactly what I was looking for (factoring out common middleware and then reusing them) but I discounted Alice because it wasn't mentioned anywhere in the README (and I guess I'm not familiar enough to have extrapolated that). Would you be fine with adding an example of reusing middleware in that manner to the README?
