### ISSUE TITLE
Blog post URL is not working

### ISSUE THREAD

**Issue by asaqib27** [justinas/alice#53]
**Issue**
Blog post URL provided in README.md is not working and throwing 404 error.
There is a slash at the end of URL that causes this issue. 
Possibly, the server has configured routes in this way thus it is expected behavior at blog (server).

**Solution**
Need to remove last slash from URL

**Comment by justinas** [comment]
Hi Abdul,

Thank you so much for notifying me about this. I recently modified the configuration of my web server and broke such links. However, since there are many links like this in the wild, I have reverted to previous configuration. So, no need for a change to the README, but thanks a lot for bringing this to my attention!
